-- MySQL Script generated by MySQL Workbench
-- 02/19/15 11:00:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `id` INT NOT NULL,
  `Date` DATE NULL,
  `FacebookMessage` VARCHAR(45) NULL,
  `TwitterMessage` VARCHAR(45) NULL,
  `TextMessage` VARCHAR(45) NULL,
  `EventType` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EventType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EventType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EventType` (
  `id` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Receiver` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Receiver` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Facebook` VARCHAR(45) NULL,
  `Twitter` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event_has_Receiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Event_has_Receiver` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Event_has_Receiver` (
  `Event_id` INT NOT NULL,
  `Receiver_id` INT NOT NULL,
  PRIMARY KEY (`Event_id`, `Receiver_id`),
  INDEX `fk_Event_has_Receiver_Receiver1_idx` (`Receiver_id` ASC),
  INDEX `fk_Event_has_Receiver_Event1_idx` (`Event_id` ASC),
  CONSTRAINT `fk_Event_has_Receiver_Event1`
    FOREIGN KEY (`Event_id`)
    REFERENCES `mydb`.`Event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_has_Receiver_Receiver1`
    FOREIGN KEY (`Receiver_id`)
    REFERENCES `mydb`.`Receiver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;